In [2]:
import numpy as np


In [3]:
a=np.arange(2,10)
print(a)

[2 3 4 5 6 7 8 9]


In [4]:
a[1]

3

In [5]:
a[1:3]

array([3, 4])

In [6]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.std()

2.29128784747792

In [9]:
from numpy import*
import time
def trad_version():
    t1=time.time()
    x=range(1000000)
    y=range(1000000)
    z=[]
    for i in range(len(x)):
        z.append(x[i]+y[i])
        
        return time.time()-t1
trad_version()

0.0

In [10]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [11]:
lst1=[10,29,30,23]

arr=np.array(lst1)

In [12]:
arr

array([10, 29, 30, 23])

In [13]:
arr.dtype

dtype('int32')

In [14]:
arr.astype(float)

array([10., 29., 30., 23.])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr2=np.arange(0,100,5)
print(arr2)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [17]:
arr2.shape

(20,)

In [18]:
arr3=np.zeros(10)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr3=np.ones(4)
arr3

array([1., 1., 1., 1.])

In [20]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [21]:
b=np.array([10,20,30])
np.repeat(b,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [22]:
np.full(6,10)

array([10, 10, 10, 10, 10, 10])

In [23]:
ar1=np.arange(1,20)
ar1[ar1%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [25]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [26]:
np.random.random(4)

array([0.64042566, 0.80976107, 0.88660202, 0.51118252])

In [27]:
np.random.randint(0,400,3)

array([263, 232,  71])

In [28]:
np.random.seed(124)
np.random.randint(0,100,10)

array([78, 28, 17,  7, 66, 41, 64, 20, 28, 78])

In [29]:
f1=np.random.uniform(5,10,size=(10))
f1

array([5.90716633, 9.90078715, 7.1398642 , 5.49810409, 9.37290823,
       7.62317744, 9.13440996, 7.87897047, 6.35509448, 5.35197396])

In [30]:
np.floor(f1)

array([5., 9., 7., 5., 9., 7., 9., 7., 6., 5.])

In [31]:
f1.astype(int)

array([5, 9, 7, 5, 9, 7, 9, 7, 6, 5])

In [32]:
b2=np.random.randn(10)  #random disturbition
b2

array([-0.18509152,  0.20666437,  0.867818  , -0.64357675, -0.61578191,
        0.76607849,  1.06971368,  0.18607856, -0.75561754, -0.65159189])

In [33]:
for index, value in np.ndenumerate(arr):
    print(index,value)

(0,) 10
(1,) 29
(2,) 30
(3,) 23


In [34]:
arr.sum()

92

In [35]:
np.cumsum(arr2)  #kümülatif toplama

array([  0,   5,  15,  30,  50,  75, 105, 140, 180, 225, 275, 330, 390,
       455, 525, 600, 680, 765, 855, 950])

In [36]:
#min #max  # argmin #argmax #mean #median #var()
np.max(arr2)

95

In [37]:
ar=np.arange(0,20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
rep1=np.where(ar%2==0, 0 , ar)

In [39]:
rep1


array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [40]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
a=np.array([10,np.nan,20,30,40,np.nan,90,np.inf])

In [42]:
a

array([10., nan, 20., 30., 40., nan, 90., inf])

In [43]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [44]:
np.isnan(a).any()

True

In [46]:
listem=np.array([10,11,12])
listem

array([10, 11, 12])

In [80]:
i=0
while i<7:
    q=((np.concatenate((q,listem),axis=0)))
    i=i+1

In [81]:
q

array([10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11,
       12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10, 11, 12, 10,
       11, 12, 10, 11, 12, 10, 11, 12])