In [1]:
import numpy as np

In [2]:
a=np.zeros(20)
a


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [5]:
a.reshape(5,-1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b=np.repeat(1,20)
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
b.reshape(2,-1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [10]:
np.vstack([a,b])  #vertical stack

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [11]:
np.hstack([a,b])    #horizontal stack

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [15]:
c1=np.array([10,20,30,40,50,60])
c2=np.array([12,20,33,40,60,55])


In [16]:
np.intersect1d(c1,c2)   #2 dizideki ortak elemanı bulan fonksyon

array([20, 40, 60])

In [17]:
np.setdiff1d(c1,c2)  # c1in c2den farkı

array([10, 30, 50])

In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array([1,3,5,4,2,1])

In [20]:
np.where([a==b])

(array([], dtype=int64), array([], dtype=int64))

In [22]:
a1=np.arange(0,60)
a1[np.where(((a1>20)&(a1<35))|(a1%10==0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [23]:
a1[np.where(np.logical_and(a1>20,a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [24]:
a=np.array([10,20,30,40,50,60,70])

In [25]:
np.isin(a,[11,20])   # dizi icerisinde eleman arama

array([False,  True, False, False, False, False, False])

In [26]:
a[np.isin(a,20)]

array([20])

In [28]:
a4=np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [29]:
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [30]:
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [34]:
a3=np.array([[10,20,30],[25,35,45],[345,121,543]])
a3

array([[ 10,  20,  30],
       [ 25,  35,  45],
       [345, 121, 543]])

In [35]:
a3[::-1]        #satırı tersten al

array([[345, 121, 543],
       [ 25,  35,  45],
       [ 10,  20,  30]])

In [37]:
a3[:,::-1]    #sutunu terse al

array([[ 30,  20,  10],
       [ 45,  35,  25],
       [543, 121, 345]])

In [38]:
a3[::-1,::-1]  #hem satır hem sutun degistir

array([[543, 121, 345],
       [ 45,  35,  25],
       [ 30,  20,  10]])

## sıralama

In [39]:
np.sort(a)  #ascending

array([10, 20, 30, 40, 50, 60, 70])

In [40]:
np.sort(a3)

array([[ 10,  20,  30],
       [ 25,  35,  45],
       [121, 345, 543]])

In [41]:
np.sort(a3,axis=1)

array([[ 10,  20,  30],
       [ 25,  35,  45],
       [121, 345, 543]])

In [42]:
c=np.sort(a)   #descending
c=c[::-1]
c

array([70, 60, 50, 40, 30, 20, 10])

In [46]:
p4=np.loadtxt('AIUP\data\sample.txt',dtype=np.integer)


FileNotFoundError: AIUP\data\sample.txt not found.

In [48]:
p7=np.arange(10,100,11)
p7

array([10, 21, 32, 43, 54, 65, 76, 87, 98])

In [49]:
np.savetxt('1805AUIP.csv',p7,delimiter=',')

In [52]:
p8=np.arange(0,121).reshape(11,11)
p8

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [54]:
p9=np.load("test1805auıp.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'test1805auıp.npy'

## vektör islemleri


In [58]:
v1=np.array([1,2])
v2=np.array([3,4])
v3=v1+v2
#v3=np.add(v1,v2)
print('V3=',v3)

V3= [4 6]


In [59]:
a1=[5,6,7]
a2=[4,5,8]
np.multiply(a1,a2)

array([20, 30, 56])

In [61]:
#DOTPRODUCT

a1=np.array([1,2,3])
a2=np.array([4,5,6])
dotp=a1@a2
dotp

32

In [62]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
dotp=np.dot(a1,a2)
dotp

32

In [64]:
v3=np.array([1,2,3,4,5,6])    #uzunluk
length=np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [67]:
v1=[2,3]      #normalizasyon
length_v1=np.sqrt(np.dot(v1,v1))
normv1=v1/length_v1
length_v1,normv1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [68]:
normv1=v1/np.linalg.norm(v1)
normv1

array([0.5547002 , 0.83205029])

In [69]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
np.random.randint(0,500,(10,10))

array([[279, 467, 480,  17, 350, 396, 323,  82, 141, 341],
       [464, 405, 398, 285, 384, 149,  84, 265, 167, 102],
       [408, 151,  31, 336, 359,  62,  17, 472, 384, 124],
       [  5,  26,  53, 399, 305,  91, 265, 472, 351, 181],
       [231, 443, 192,  60, 356,  71, 238, 448, 214, 395],
       [128, 151,  42, 132, 443, 130, 483, 221, 110, 267],
       [296,  92, 122,  46,  86,  80, 482, 318, 357, 234],
       [117,  75,  65, 475, 236, 339, 442,  18, 420, 316],
       [420, 323, 408, 264, 186, 249, 258, 480, 101, 387],
       [354, 209, 484,  68, 470, 408, 162, 406, 411, 321]])

In [76]:
I=np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [78]:
D=np.diag([1,2,3,4,5,6])
D

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [81]:
M=np.random.randn(5,5)
M

array([[-0.94094592,  1.81436305,  0.82179266, -0.2707652 ,  0.86491803],
       [ 1.08449649, -0.88779173, -0.19635256, -1.09927665,  1.4029318 ],
       [ 0.45038129,  1.02632942,  0.29907958,  1.3743351 ,  1.02021822],
       [-0.4013311 ,  0.27961026, -0.79812759,  0.05959883, -0.21054869],
       [-1.24260591,  0.08095341,  1.10619061,  2.08526185, -1.96493071]])

In [83]:
U=np.triu(M)
U

array([[-0.94094592,  1.81436305,  0.82179266, -0.2707652 ,  0.86491803],
       [ 0.        , -0.88779173, -0.19635256, -1.09927665,  1.4029318 ],
       [ 0.        ,  0.        ,  0.29907958,  1.3743351 ,  1.02021822],
       [ 0.        ,  0.        ,  0.        ,  0.05959883, -0.21054869],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.96493071]])

In [87]:
L=np.tril(M)
L

array([[-0.94094592,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.08449649, -0.88779173,  0.        ,  0.        ,  0.        ],
       [ 0.45038129,  1.02632942,  0.29907958,  0.        ,  0.        ],
       [-0.4013311 ,  0.27961026, -0.79812759,  0.05959883,  0.        ],
       [-1.24260591,  0.08095341,  1.10619061,  2.08526185, -1.96493071]])

In [88]:
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [89]:
np.random.uniform(10,20,size=(5,5))

array([[13.28197013, 18.14947949, 15.24417946, 18.35285847, 11.93786659],
       [11.51931441, 15.19256353, 13.06615959, 10.56805053, 11.42050862],
       [10.2314867 , 13.11192259, 13.5292884 , 15.19459046, 18.02284704],
       [11.52553863, 17.79933833, 19.43594596, 10.73050246, 10.84199259],
       [15.00630807, 16.06016996, 15.12143755, 16.26711769, 10.96039019]])

In [91]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [92]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [93]:
M=np.array([[1,2,3],[4,-3,6],[7,8,0]])
N=np.array([[1,1,1],[2,2,2],[3,3,3]])
C=M+N
print(C)


[[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]


In [100]:
C=M-N
C

array([[ 0,  1,  2],
       [ 2, -5,  4],
       [ 4,  5, -3]])

In [102]:
C=np.subtract(M,N,dtype=np.float64)
C

array([[ 0.,  1.,  2.],
       [ 2., -5.,  4.],
       [ 4.,  5., -3.]])

In [105]:
M=np.array([[1,2,3],[4,-3,6],[7,8,0]])
M

array([[ 1,  2,  3],
       [ 4, -3,  6],
       [ 7,  8,  0]])

In [106]:
C=10
M*10


array([[ 10,  20,  30],
       [ 40, -30,  60],
       [ 70,  80,   0]])

In [107]:
##transpoze
print(np.transpose(M))

[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [108]:
#or

print(M.T)

[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [109]:
#determinant
M=np.array([[1,2,3],[4,-3,6],[7,8,0]])
print(np.linalg.det(M))


195.0


In [110]:
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [112]:
N=np.array([[1,1,1],[2,2,2],[3,3,3]])
M/N

array([[ 1.        ,  2.        ,  3.        ],
       [ 2.        , -1.5       ,  3.        ],
       [ 2.33333333,  2.66666667,  0.        ]])

In [113]:
np.divide(M,N)

array([[ 1.        ,  2.        ,  3.        ],
       [ 2.        , -1.5       ,  3.        ],
       [ 2.33333333,  2.66666667,  0.        ]])

In [114]:
M1=np.array([[1,2],[4,5]])
M1


array([[1, 2],
       [4, 5]])

In [116]:
M1@M1@M1


array([[ 57,  78],
       [156, 213]])

## TENSOR

In [118]:
T1=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]]
])

T1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [119]:
T2=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,10,10],[10,10,10],[10,10,10]],
    [[20,20,20],[20,20,20],[20,20,20]]
])
T2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[20, 20, 20],
        [20, 20, 20],
        [20, 20, 20]]])

In [121]:
A=T1+T2
A

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[11, 11, 11],
        [11, 11, 11],
        [11, 11, 11]],

       [[22, 22, 22],
        [22, 22, 22],
        [22, 22, 22]]])